name: segundo Workflow
on: push
jobs:
    teste:
        runs-on: ubuntu-latest
        steps:
            - name: get checkout
              uses: actions/checkout@v3
            - name: install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencias
              run: npm ci
            - name: run teste
              run: npm test
            
            - name: Criar branch release
              run: |
                git checkout -b release2
                git push origin release2
                
            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                token: ${{ secrets.TOKEN }}  # Token para autenticação
                branch: 'release2'  # Nome da branch que será criada para o PR
                base: 'develop'  # Branch base para o PR
                title: 'Automated PR - Atualizações após execução do workflow'
                body: 'Este PR foi criado automaticamente após a execução do workflow.' 
