name: segundo Workflow
on: push
jobs:
    teste:
        runs-on: ububtu-latest
        steps:
            - name: get checkout
              uses: actions/checkout@v3
            - name: install nodejs
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: install dependencias
              run: npmci
            - name: run teste
              run: npm test